<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Canvaas</AssemblyName>
    <RootNamespace>Canvaas</RootNamespace>
    <Version>0.0.1</Version>
    <Product>Canvaas</Product>
    <Company>Canvaas</Company>
  </PropertyGroup>

</Project>
